name: Publish
on:
  workflow_run:
    workflows: [CI]
    branches: [main]
    types: [completed]

concurrency: ${{ github.workflow }}-${{ github.ref }}

permissions:
  contents: write
  pull-requests: write
  issues: write
  repository-projects: write
  id-token: write

jobs:
  publish:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    environment:
      name: pypi
      url: https://pypi.org/p/melodi-connector

    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 10
      - uses: actions/setup-node@v3
        with:
          node-version: 22.x
          cache: "pnpm"

      - run: pnpm install --frozen-lockfile
      - name: Create Release Pull Request or Publish
        id: changesets
        uses: changesets/action@v1
        with:
          publish: pnpm run release
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
      - name: Store the distribution packages
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: packages/melodi-connector-python/dist
      - name: Download all the dists
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: packages/melodi-connector-python/dist
      - name: Move downloaded dists to repository root 'dist'
        run: |
          # create a root-level dist folder where many PyPI actions expect it
          mkdir -p dist
          # copy all downloaded distribution files into root dist
          if [ -d "packages/melodi-connector-python/dist" ]; then
            cp -r packages/melodi-connector-python/dist/* dist/ || true
          fi
      - name: Release on PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
